### ISSUE TITLE
sfa_get_shares without fyear delivers only current year for SimFin+ users

### ISSUE THREAD

**Issue by ogig33** [matthiasgomolka/simfinapi#36] opened 2021-10-31 13:10 UTC
# Problem description
The sfa_get_shares function only delivers data of current period, despite `sfplus` set correctly and `fyear` omitted.

# Expected behavior
As per the documentation, if `fyear` parameter is omitted, all periods should be submitted.
https://cran.r-project.org/web/packages/simfinapi/simfinapi.pdf

# How to reproduce

```r
library(simfinapi)
sfa_set_api_key(api_key = "mykeyremoved")
sfa_set_cache_dir(path = "/Users/as/Documents/Aktienberichte/R")
sfa_set_sfplus(sfplus = TRUE)

sh_data <- sfa_get_shares(tickers, type = "wa-basic") # does not return all years if period is empty??
print(sh_data)
```

# Specs
* macOS 12.0.1
* simfinapi 0.2.0

**Comment by matthiasgomolka** [comment] 2021-10-31 15:05
Confirmed. Thanks for the report. `fyear` defaults to `"fy"`, independently of `sfplus`. I'll change the default so it respects your `sfplus` setting.

**Comment by matthiasgomolka** [comment] 2021-10-31 17:27
After checking on https://simfin.com/api/v2/documentation/#tag/Company/paths/~1companies~1shares/get I noticed that omitting `period` is not reserved for SimFin+ Users in this context (it is for statements!).

So I changed the default to `NULL` and `sfa_get_shares()` now retrieves all `period`s by default.

To install the development version containing the fix, use: 
```r 
remotes::install_github("https://github.com/matthiasgomolka/simfinapi/tree/development")
```

Just a sidenote: The [{reprex} package](https://reprex.tidyverse.org/) makes it easier to create reproducible examples.

**Comment by ogig33** [comment] 2021-11-01 09:41
Thanks for the extremely fast fix and thanks for the hint to repex!

**Comment by ogig33** [comment] 2021-11-01 10:22
While testing, I noticed that in the development version now all period types are delivered (FY and quarters).
This seems inconsistent with `sfa_get_statements` behaviour, which delivers only FY statements by default when `fyear` is omitted. It works for me nevertheless as I can use the `period` parameter to achieve the same outcome, just wanted to let you know as I am not sure this is intended behaviour.

**Comment by matthiasgomolka** [comment] 2021-11-01 18:10
As written above, I changed the default:

> So I changed the default to NULL and sfa_get_shares() now retrieves all periods by default.

I get that this is inconsistent with `sfa_get_statements()` and I was wondering if this decision was useful or not. Please note that the API is inconsistent here as is allows all users to download all kinds of `fyear` at once for shares, but not for statements. Here is the trade-off:

*Pro:* 
- All users get as much information as possible using the defaults.

*Contra:*
- Inconsistent with `sfa_get_statements()`.

Please comment, if you value consistency over completeness or vice versa.

**Comment by ogig33** [comment] 2021-11-01 20:32
I prefer consistency.
There should not be much impact, as users who need annual and quarterly data in one table, already have that logic in their code due to the way `sfa_get_statements()` works. Just my 50 ct.

**Comment by matthiasgomolka** [comment] 2021-11-06 16:01
Thanks for your perspective. I'll think about it.

**Comment by matthiasgomolka** [comment] 2023-03-04 11:47
Since I'm preparing for a majopr update to adapt simfinapi to the newly release API V3, I won't fix any V2 issues any more.

**Closed by matthiasgomolka** 2023-03-04 11:47 UTC
Labels: bug
