### ISSUE TITLE
A dependency package called failed to install - RcppSimdJson 

### ISSUE THREAD

**Issue by anuragjalan** [matthiasgomolka/simfinapi#12] opened 2020-10-16 13:21 UTC
Brief description of the problem--- I am unable to install simfinapi as one of the package its dependent on fails to install - RcppSimdJson

```r
if(!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, data.table,dplyr,rmarkdown,quantmod,Quandl,simfinapi)

```
the error message as seen 
ERROR: dependency 'RcppSimdJson' is not available for package 'simfinapi'
* removing 'C:/Users/anura/Documents/R/win-library/3.6/simfinapi'

The downloaded source packages are in
	‘C:\Users\anura\AppData\Local\Temp\RtmpQxic3y\downloaded_packages’
Warning messages:
1: In utils::install.packages(package, ...) :
  installation of package ‘simfinapi’ had non-zero exit status
2: In p_install(package, character.only = TRUE, ...) : 
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘simfinapi’
4: In pacman::p_load(ggplot2, data.table, dplyr, rmarkdown, quantmod,  :
  Failed to install/load:
simfinapi

**Comment by Plebejer** [comment] 2020-10-16 18:34
I can't reproduce your error. Please post a reproducible example (see https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example). 

What happens if you use `install.packages("simfinapi")`?

At first sight, it does not seem to be an issue with `simfinapi`, but with `RcppSimdJson`.

**Comment by knapply** [comment] 2020-10-25 23:16
Without a `sessionInfo()` output, I can't tell, but it's probably because you're using a pre-4.0 version of R.  Since you're on Windows, that means you're relying on the old tool chain that uses a compiler based on GCC 4.9.3. 

simdjson itself needs a modern C++ compiler and supports GCC 7+, which is what RcppSimdJson also supports (with the caveat that we also currently use some C++17 goodies, but we still test on GCCs 7-10).

@anuragjalan, I suspect you just need to upgrade your version of R.

**Comment by matthiasgomolka** [comment] 2020-10-26 20:04
Without additional information, it's impossible to assist. Closing the issue...

**Closed by matthiasgomolka** 2020-10-26 20:04 UTC
